/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FilterList {
        "keyword": string;
    }
    interface MyComponent {
    }
}
declare global {
    interface HTMLFilterListElement extends Components.FilterList, HTMLStencilElement {
    }
    var HTMLFilterListElement: {
        prototype: HTMLFilterListElement;
        new (): HTMLFilterListElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "filter-list": HTMLFilterListElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface FilterList {
        "keyword"?: string;
    }
    interface MyComponent {
    }
    interface IntrinsicElements {
        "filter-list": FilterList;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "filter-list": LocalJSX.FilterList & JSXBase.HTMLAttributes<HTMLFilterListElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
